name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/release.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o currency-loader-windows-amd64.exe

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o currency-loader-darwin-amd64

      - name: Build for Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o currency-loader-linux-amd64

      - name: Build for Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build -o currency-loader-linux-arm64

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ env.CURRENT_DATE }}
          release_name: Release ${{ env.CURRENT_DATE }}
          draft: false
          prerelease: false

      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./currency-loader-windows-amd64.exe
          asset_name: currency-loader-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./currency-loader-darwin-amd64
          asset_name: currency-loader-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux AMD64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./currency-loader-linux-amd64
          asset_name: currency-loader-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./currency-loader-linux-arm64
          asset_name: currency-loader-linux-arm64
          asset_content_type: application/octet-stream